name: Radar Web UI deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and deploying Radar Web UI
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.4

      - name: Installation of dependencies
        run: npm install

      - name: Build
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        working-directory: ./public
        run: aws s3 sync . s3://sbx-radar-radarwebstackn-webappdeploymentbucketf2-18zb4jb1xru6e --acl bucket-owner-full-control
